spring:
  application:
    name: ocare
  
  profiles:
    active: local
  
  # 로컬 개발 환경 설정 (H2 인메모리 DB)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# 서버 설정
server:
  port: 8080